spring.application.name=MyTodoApp

# Port de l'application
server.port=8080

# URL de connexion à la base de données
spring.datasource.url=jdbc:mariadb://localhost:3300/mytodolist_db

# Identifiant MariaDB
spring.datasource.username=root

# Mot de passe MariaDB
spring.datasource.password=fms2025

# Driver JDBC MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Met à jour automatiquement les tables sans supprimer les données existantes
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL dans la console
spring.jpa.show-sql=true

# Formate le SQL affiché dans la console
spring.jpa.properties.hibernate.format_sql=true

# Dialecte Hibernate pour MariaDB
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Désactive le cache Thymeleaf en développement
spring.thymeleaf.cache=false

# Niveau de log SQL Hibernate
logging.level.org.hibernate.SQL=DEBUG

# Affiche les valeurs passées dans les requêtes préparées
logging.level.org.hibernate.orm.jdbc.bind=TRACE
